# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: 'Deployment VPS AWS'
        deployment: staging
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: 'admin'
              SERVER: '18.136.126.248'
              PORT: '22'
              COMMAND: '. build_desa_lampenai.sh'
